<?php
declare(strict_types=1);

/** @return array<string,array<string,list<string>>> */
function cx_vehicle_model_catalog_data(): array
{
    return [
        'otomobil' => [
            'Audi' => ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron'],
            'BMW' => ['1 Serisi', '2 Serisi', '3 Serisi', '320i', '4 Serisi', '5 Serisi', '520i', 'X1', 'X2', 'X3', 'X5', 'X6', 'i3', 'i4', 'iX'],
            'Mercedes-Benz' => ['A-Serisi', 'B-Serisi', 'C-Serisi', 'C200', 'E-Serisi', 'S-Serisi', 'CLA', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS'],
            'Volkswagen' => ['Polo', 'Golf', 'Passat', 'Arteon', 'T-Cross', 'T-Roc', 'Tiguan', 'Touareg', 'ID.3', 'ID.4'],
            'Ford' => ['Fiesta', 'Focus', 'Puma', 'Kuga', 'Mondeo', 'Mustang', 'Ranger', 'Tourneo'],
            'Toyota' => ['Yaris', 'Corolla', 'C-HR', 'RAV4', 'Camry', 'Land Cruiser', 'Hilux'],
            'Renault' => ['Clio', 'Megane', 'Captur', 'Kadjar', 'Arkana', 'Taliant', 'Austral'],
            'Fiat' => ['500', 'Panda', 'Tipo', 'Egea', 'Doblo', '500X', '500L'],
            'Hyundai' => ['i10', 'i20', 'i30', 'Bayon', 'Kona', 'Tucson', 'Santa Fe'],
            'Citroën' => ['C1', 'C3', 'C3 Aircross', 'C4', 'C5 Aircross', 'Berlingo'],
            'Peugeot' => ['208', '2008', '308', '3008', '408', '5008', '508'],
            'Opel' => ['Corsa', 'Astra', 'Mokka', 'Crossland', 'Grandland', 'Insignia'],
            'Nissan' => ['Micra', 'Juke', 'Qashqai', 'X-Trail', 'Leaf', 'Navara'],
            'Honda' => ['Jazz', 'Civic', 'HR-V', 'CR-V', 'Accord'],
            'Kia' => ['Picanto', 'Rio', 'Ceed', 'Stonic', 'Sportage', 'Sorento', 'EV6'],
            'Skoda' => ['Fabia', 'Scala', 'Octavia', 'Kamiq', 'Karoq', 'Kodiaq', 'Superb'],
            'Seat' => ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco'],
            'Volvo' => ['XC40', 'XC60', 'XC90', 'S60', 'S90', 'V60', 'V90'],
            'Tesla' => ['Model 3', 'Model Y', 'Model S', 'Model X'],
            'Togg' => ['T10X'],
            'Mini' => ['Cooper', 'Countryman', 'Clubman'],
            'Suzuki' => ['Swift', 'Vitara', 'S-Cross', 'Jimny'],
            'Mazda' => ['2', '3', '6', 'CX-3', 'CX-30', 'CX-5'],
            'Dacia' => ['Sandero', 'Duster', 'Jogger', 'Spring'],
            'Mitsubishi' => ['Space Star', 'ASX', 'Eclipse Cross', 'Outlander', 'L200'],
            'Jeep' => ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler'],
            'Land Rover' => ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Evoque'],
            'Porsche' => ['718', '911', 'Panamera', 'Macan', 'Cayenne', 'Taycan'],
            'Cupra' => ['Born', 'Formentor', 'Leon', 'Ateca'],
            'BYD' => ['Atto 3', 'Han', 'Seal'],
            'Alfa Romeo' => ['Giulia', 'Stelvio', 'Tonale'],
            'Subaru' => ['Impreza', 'XV', 'Forester', 'Outback'],
            'Lexus' => ['UX', 'NX', 'RX', 'ES', 'IS'],
            'Jaguar' => ['XE', 'XF', 'F-Pace', 'E-Pace', 'I-Pace'],
            'Diğer' => ['Diğer'],
        ],
        'motosiklet' => [
            'Honda' => ['CBR', 'CB', 'CB650R', 'PCX', 'Forza', 'Africa Twin', 'NC', 'Gold Wing', 'X-ADV'],
            'Yamaha' => ['MT-03', 'MT-07', 'MT-09', 'R25', 'R3', 'R6', 'NMAX', 'XMAX', 'Tracer', 'Tenere'],
            'Kawasaki' => ['Ninja', 'Ninja 650', 'Z400', 'Z650', 'Z900', 'Versys', 'Vulcan', 'Eliminator'],
            'Suzuki' => ['GSX-R', 'GSX-S', 'V-Strom', 'Burgman', 'Address', 'Hayabusa'],
            'BMW' => ['G 310 R', 'F 850 GS', 'R 1250 GS', 'R 1250 RT', 'S 1000 RR', 'S 1000 XR', 'C 400 X'],
            'Ducati' => ['Monster', 'Panigale', 'Multistrada', 'Scrambler', 'Diavel', 'Streetfighter'],
            'KTM' => ['390 Duke', '790 Duke', '1290 Super Duke', '390 Adventure', '890 Adventure'],
            'Harley-Davidson' => ['Sportster', 'Softail', 'Touring', 'Pan America', 'Street'],
            'Aprilia' => ['RS', 'Tuono', 'SR', 'Shiver', 'Tuareg'],
            'Benelli' => ['TRK', 'Leoncino', 'BN', 'TNT'],
            'Husqvarna' => ['Svartpilen', 'Vitpilen', 'Norden', 'TE', 'FE'],
            'Indian' => ['Scout', 'Chief', 'Challenger', 'FTR'],
            'Piaggio' => ['Beverly', 'Medley', 'Liberty', 'MP3'],
            'Royal Enfield' => ['Classic', 'Meteor', 'Hunter', 'Himalayan', 'Interceptor'],
            'Triumph' => ['Street Triple', 'Speed Triple', 'Tiger', 'Bonneville', 'Rocket'],
            'Vespa' => ['Primavera', 'GTS', 'Sprint', 'Elettrica'],
            'Diğer' => ['Diğer'],
        ],
        'bisiklet' => [
            'Trek' => ['Marlin', 'Fuel EX', 'Domane', 'Madone', 'FX', 'Verve', 'Dual Sport'],
            'Giant' => ['Talon', 'Escape', 'Defy', 'TCR', 'Trance', 'Revolt', 'ATX'],
            'Specialized' => ['Rockhopper', 'Stumpjumper', 'Allez', 'Sirrus', 'Turbo', 'Chisel'],
            'Cannondale' => ['Trail', 'Synapse', 'Quick', 'Scalpel', 'Topstone', 'Bad Boy'],
            'Bianchi' => ['Oltre', 'Sprint', 'Via Nirone', 'Impulso', 'Arcadex'],
            'Cube' => ['Aim', 'Attention', 'Acid', 'Agree', 'Stereo', 'Reaction'],
            'Decathlon' => ['Rockrider', 'Triban', 'Riverside', 'Van Rysel', 'Elops'],
            'Scott' => ['Scale', 'Spark', 'Addict', 'Genius', 'Aspect', 'Contessa'],
            'Merida' => ['Big Nine', 'Big Seven', 'Scultura', 'Silex', 'Crossway'],
            'Canyon' => ['Neuron', 'Spectral', 'Endurace', 'Grizl', 'Grand Canyon', 'Pathlite'],
            'Diğer' => ['Diğer'],
        ],
        'antika-arac' => [
            'Mercedes-Benz' => ['280S', 'W108', 'W123', 'SL', 'Pagoda', '190SL'],
            'Ford' => ['Mustang', 'Thunderbird', 'Model T', 'Escort', 'Capri'],
            'Volkswagen' => ['Beetle', 'Type 2', 'Golf Mk1', 'Karmann Ghia'],
            'Cadillac' => ['Series 62', 'Eldorado', 'DeVille', 'Fleetwood'],
            'Porsche' => ['911 Carrera', '911', '356', '914', '928'],
            'BMW' => ['2002', 'E30', 'E9', 'Isetta', '507'],
            'Chevrolet' => ['Corvette', 'Camaro', 'Bel Air', 'Impala'],
            'Fiat' => ['500', '124 Spider', '126', '131'],
            'Jaguar' => ['E-Type', 'XK', 'Mark 2', 'XJ6'],
            'Rolls Royce' => ['Silver Shadow', 'Silver Cloud', 'Phantom'],
            'Diğer' => ['Diğer'],
        ],
        'ticari' => [
            'Ford' => ['Transit', 'Transit Custom', 'Transit Connect', 'Ranger', 'F-Max', 'Cargo'],
            'Mercedes-Benz' => ['Sprinter', 'Vito', 'Citan', 'Actros', 'Atego', 'Axor', 'Vario'],
            'Volkswagen' => ['Crafter', 'Caddy', 'Transporter', 'Amarok', 'LT'],
            'Fiat' => ['Ducato', 'Doblo', 'Fiorino', 'Scudo', 'Talento'],
            'Isuzu' => ['N-Series', 'NPR', 'NLR', 'D-Max'],
            'Renault' => ['Master', 'Trafic', 'Kangoo', 'Midlum', 'Premium'],
            'Iveco' => ['Daily', 'Eurocargo', 'Stralis', 'S-Way'],
            'MAN' => ['TGE', 'TGS', 'TGX', 'TGL'],
            'Peugeot' => ['Boxer', 'Partner', 'Expert', 'Bipper'],
            'Scania' => ['R-Series', 'P-Series', 'G-Series', 'L-Series'],
            'Volvo' => ['FH', 'FM', 'FL', 'FE', 'VNL'],
            'Diğer' => ['Diğer'],
        ],
    ];
}
