<?php
return [
    'name' => 'BenimBazar',
    'tagline' => 'Al, sat, kazançlı çık!',
    'url' => 'http://changex.mehmetfer.com.tr',
    'timezone' => 'Europe/Istanbul',
    'locale' => 'tr_TR',
    'charset' => 'UTF-8',
    'debug' => false,
    /** Canli sunucuda true; yerel gelistirmede false yapin (kurulum.php / test.php acilir). */
    'production' => true,
    /** Mesajlasma tamamlaninca true yapin. */
    'messages_enabled' => false,
    /** true yapinca superadmin icin bilinen zayif sifreler (14531453 vb.) engellenir. */
    'block_weak_superadmin_password' => false,
    'session_name' => 'changex_session',
    'session_lifetime' => 86400 * 30,
    'session_path' => '/',
    'session_domain' => '',
    'session_secure' => null,
    'session_samesite' => 'Lax',
    'session_save_path' => __DIR__ . '/../storage/sessions',
    'listing_no_base' => 1000000000,
    'listing_ttl_days' => 90,
    'feed_limit' => 120,
    'view_salt' => 'changex-view-v1',
    'uploads_path' => __DIR__ . '/../uploads',
    'uploads_url' => '/uploads',
    'max_upload_bytes' => 5 * 1024 * 1024,
    'allowed_upload_types' => ['image/jpeg', 'image/png', 'image/webp'],
    'brand_assets' => [
        'logo_horizontal' => '/assets/branding/logo-horizontal-transparent.png',
        'logo_vertical' => '/assets/branding/logo-vertical-transparent.png',
        'logo_icon' => '/assets/branding/logo-icon.png',
        'favicon' => '/assets/branding/favicon-512.png',
        'favicon_32' => '/assets/branding/favicon-32.png',
        'watermark' => '/assets/branding/watermark-logo.png',
    ],
    /** Filigran: upload aninda dosyaya yazilir; CSS katmani kapali. */
    'photo_watermark' => [
        'enabled' => false,
        'burn_on_upload' => true,
        'logo' => '/assets/branding/watermark-logo.png',
        'burn_logo' => '/assets/branding/watermark-logo.png',
        'burn_width_ratio' => 0.18,
        'burn_opacity' => 30,
        'burn_margin_px' => 14,
        'burn_blur_passes' => 2,
        'burn_jpeg_quality' => 88,
        'opacity_detail' => 0,
        'opacity_card' => 0,
        'opacity_thumb' => 0,
        'blur_px' => 0,
        'rotate_deg' => 0,
    ],
];
